# Generated by Django 3.2.12 on 2022-03-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_feedback_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('purchase_price', models.IntegerField(blank=True, null=True, verbose_name='цена покупки')),
                ('selling_price', models.IntegerField(blank=True, null=True, verbose_name='цена продажи')),
            ],
        ),
    ]
