# Generated by Django 3.2.12 on 2022-03-16 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('start_work', models.DateField(auto_now_add=True, null=True)),
                ('work_experience', models.CharField(max_length=100)),
                ('process_work', models.TextField(blank=True, null=True, verbose_name='process work')),
                ('completed_work', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPerformed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_work', models.DateField(auto_now_add=True, null=True)),
                ('finish_work', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('In progress', 'In progress'), ('Completed', 'Completed')], max_length=50, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.product')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.warehouse')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.worker')),
            ],
        ),
    ]
