# Generated by Django 3.2.12 on 2022-03-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_worker_workperformed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='completed_work',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='process_work',
        ),
    ]
