# Generated by Django 3.2.12 on 2022-03-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_auto_20220316_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='workperformed',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
