# Generated by Django 3.2.12 on 2022-03-17 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_workperformed_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Currency name')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Currency code')),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.IntegerField(blank=True, null=True, verbose_name='January')),
                ('february', models.IntegerField(blank=True, null=True, verbose_name='february')),
                ('march', models.IntegerField(blank=True, null=True, verbose_name='March')),
                ('april', models.IntegerField(blank=True, null=True, verbose_name='April')),
                ('may', models.IntegerField(blank=True, null=True, verbose_name='May')),
                ('june', models.IntegerField(blank=True, null=True, verbose_name='June')),
                ('july', models.IntegerField(blank=True, null=True, verbose_name='July')),
                ('august', models.IntegerField(blank=True, null=True, verbose_name='August')),
                ('september', models.IntegerField(blank=True, null=True, verbose_name='September')),
                ('october', models.IntegerField(blank=True, null=True, verbose_name='October')),
                ('november', models.IntegerField(blank=True, null=True, verbose_name='November')),
                ('december', models.IntegerField(blank=True, null=True, verbose_name='December')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.currency')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.worker')),
            ],
        ),
    ]
