# Generated by Django 3.2.12 on 2022-03-19 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_calculation_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitsOfMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
            ],
        ),
        migrations.AddField(
            model_name='warehouse',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.unitsofmeasurement'),
        ),
    ]
