# Generated by Django 3.2.12 on 2022-03-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_auto_20220319_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workperformed',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='workperformed',
            name='warehouse',
            field=models.ManyToManyField(blank=True, to='ecom.Warehouse', verbose_name='Warehouse'),
        ),
        migrations.RemoveField(
            model_name='workperformed',
            name='worker',
        ),
        migrations.AddField(
            model_name='workperformed',
            name='worker',
            field=models.ManyToManyField(blank=True, to='ecom.Worker', verbose_name='Worker'),
        ),
    ]
