# Generated by Django 3.2.12 on 2022-03-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0014_auto_20220319_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='year',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Implementation start date'),
        ),
    ]
