# Generated by Django 3.2.12 on 2022-03-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0016_alter_calculation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='completed_work',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='worker',
            name='process_work',
            field=models.TextField(blank=True, null=True, verbose_name='process work'),
        ),
    ]
