# Generated by Django 3.2.12 on 2022-03-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0019_alter_calculation_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=40)),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.unitsofmeasurement')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.warehouse')),
                ('workPerformed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.workperformed')),
            ],
        ),
    ]
