# Generated by Django 3.2.12 on 2022-03-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0020_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workperformed',
            name='warehouse',
        ),
    ]
