# Generated by Django 3.2.12 on 2022-03-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0021_remove_workperformed_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workperformed',
            name='count',
        ),
        migrations.RemoveField(
            model_name='workperformed',
            name='uom',
        ),
    ]
