# Generated by Django 3.2.12 on 2022-03-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0023_alter_material_workperformed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='uom',
        ),
    ]
